name: maxkgapp
description: Max.kg application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:

  connectivity_plus: ^3.0.2
  share_plus: ^2.0.3
  flutter:
    sdk: flutter
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  badges: ^2.0.3
  intl: ^0.17.0
  getwidget: ^3.0.1
  percent_indicator: ^4.2.2
  sms_autofill: ^2.2.0
  pin_code_fields: ^7.4.0
  yandex_mapkit: ^3.2.0
  flutter_switch: ^0.3.2
  configurable_expansion_tile_null_safety: ^3.1.1
  timeline_tile: ^2.0.0
  youtube_player_flutter: ^8.1.1
  expansion_widget: ^0.0.3
  dotted_decoration: ^2.0.0
  cupertino_icons: ^1.0.5
  auto_size_text: ^3.0.0
  expand_widget: ^3.1.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.6
  flutter_staggered_grid_view: ^0.4.1
  cached_network_image: ^3.2.2
  google_fonts: ^3.0.1
  flutter_vector_icons: ^1.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  carousel_slider: ^4.1.1
  expandable: ^5.0.1
  animated_widgets: ^1.0.6
  flutter_swiper_view: ^1.1.8
  shimmer: ^2.0.0
  sqflite: ^2.1.0+1
  flutter_svg: any
  flutter_svg_provider: ^1.0.3
  sizer: ^2.0.15
  speech_to_text: ^6.1.0
  html: ^0.15.1
  webview_flutter: ^3.0.4
  intro_slider: ^4.2.0
  flutter_masked_text2: ^0.9.1
  time_machine: ^0.9.17
  flutter_html: ^3.0.0-alpha.6
  platform: ^3.0.1
  http: ^0.13.5
  yandex_geocoder: ^2.0.2
  flutter_native_splash: ^2.2.16


flutter_native_splash:
  background_image: assets/images/maxkg.png
  image: assets/images/max.png
  android: true


dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - assets/images/
    - assets/images/config/
    - assets/icons/
    - assets/icons/lang/
    - assets/rive/
    - assets/
    - assets/sounds/speech_to_text_listening.m4r
    - assets/sounds/speech_to_text_cancel.m4r
    - assets/sounds/speech_to_text_stop.m4r

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: litia
      fonts:
        - asset: fonts/litia.ttf
          style: italic
    - family: rounded
      fonts:
        - asset: fonts/rounded.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
          style: italic
    - family: RobotoThin
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          style: italic
    - family: MPLUSRounded1c-Black
      fonts:
        - asset: fonts/MPLUSRounded1c-Medium.ttf
          style: italic

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
